### ISSUE TITLE
related locations returns null elements if less than requested available

### ISSUE THREAD

**Issue by timoweiss** [locator-kn/ark-database#69]
![screen shot 2015-08-18 at 3 19 17 pm](https://cloud.githubusercontent.com/assets/5221667/9330972/ef494c50-45bc-11e5-9ec7-05456667c06d.png)

**Comment by timoweiss** [comment]
https://github.com/locator-kn/ark-database/blob/master/src/location/location.ts#L218
Before for-loop:
`if length < number; number = length;`

Edit: `length - 1` for requesting location

**Comment by timoweiss** [comment]
Maybe length needs to be set again after `locations`-array manipulation

**Comment by SteffenGorenflo** [comment]
implemented and tested manually
